# -*- coding: utf-8 -*-
"""calssfication project1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oK7E4cf8ZjehMkuQHfQ_t219ibdtRYwz
"""

#Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

#Load the datasets
train = pd.read_csv('/content/loan_sanction_train.csv')
test = pd.read_csv('/content/loan_sanction_test.csv')

print(train.shape)
print(test.shape)
print(train.head())

#Understand the data
print(train.info())
print(train.describe())
print(train.describe(include="object"))
print(train["Loan_Status"].value_counts())

#Exploratory Data Analysis (EDA)
#Univariate Analysis
#Loan Status Countplot
sns.countplot(data=train, x="Loan_Status")
plt.title("Loan Status Distribution")
plt.show()

#Categorical columns
categorical_columns = [
    "Gender", "Married", "Education",
    "Self_Employed", "Property_Area"
]

for col in categorical_columns:
    sns.countplot(data=train, x=col)
    plt.title(col)
    plt.xticks(rotation=45)
    plt.show()

#Numerical columns
numerical_columns = [
    "ApplicantIncome", "CoapplicantIncome", "LoanAmount"
]

for col in numerical_columns:
    sns.histplot(data=train, x=col, kde=True)
    plt.title(col)
    plt.show()

#Loan Status vs Education
#Bivariate Analysis
sns.countplot(data=train, x="Education", hue="Loan_Status")
plt.title("Education vs Loan Status")
plt.show()

#Loan Status vs Property Area
sns.countplot(data=train, x="Property_Area", hue="Loan_Status")
plt.title("Property Area vs Loan Status")
plt.show()

#Credit History vs Loan Status
sns.countplot(data=train, x="Credit_History", hue="Loan_Status")
plt.title("Credit History vs Loan Status")
plt.show()

#Income vs Loan Amount
sns.scatterplot(
    data=train,
    x="ApplicantIncome",
    y="LoanAmount",
    hue="Loan_Status"
)
plt.title("Applicant Income vs Loan Amount")
plt.show()

#Outlier Treatment
for col in ["ApplicantIncome", "CoapplicantIncome", "LoanAmount"]:
    sns.boxplot(x=train[col])
    plt.title(col)
    plt.show()

#Prepare Data for Model Building
train["Dependents"] = train["Dependents"].replace("3+", "3")
test["Dependents"] = test["Dependents"].replace("3+", "3")

for df in [train, test]:
    df["Dependents"] = pd.to_numeric(df["Dependents"], errors="coerce")
    df["Total_Income"] = df["ApplicantIncome"] + df["CoapplicantIncome"]
    df["Income_Loan_Ratio"] = (
        df["Total_Income"] / df["LoanAmount"].replace(0, np.nan)
    )

X = train.drop(columns=["Loan_Status", "Loan_ID"])
y = train["Loan_Status"].map({"N": 0, "Y": 1})

X_test = test.drop(columns=["Loan_ID"])

print(X.shape)
print(y.value_counts())
print(X_test.shape)

#Train-Test Split
X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(X_train.shape)
print(X_val.shape)

#Preprocessing Pipeline
categorical_features = X.select_dtypes(include=["object"]).columns.tolist()
numerical_features = X.select_dtypes(exclude=["object"]).columns.tolist()

numerical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("num", numerical_pipeline, numerical_features),
    ("cat", categorical_pipeline, categorical_features)
])

#Logistic Regression
logistic_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LogisticRegression(max_iter=1000, random_state=42))
])

logistic_model.fit(X_train, y_train)

y_pred = logistic_model.predict(X_val)

print("Accuracy:", accuracy_score(y_val, y_pred))
print("Precision:", precision_score(y_val, y_pred, zero_division=0))
print("Recall:", recall_score(y_val, y_pred, zero_division=0))
print("F1 Score:", f1_score(y_val, y_pred, zero_division=0))
print("Confusion Matrix:\n", confusion_matrix(y_val, y_pred))
print(classification_report(y_val, y_pred, zero_division=0))

#Stratified K-Fold Cross Validation
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

cv_scores = cross_val_score(
    logistic_model,
    X,
    y,
    cv=cv,
    scoring="accuracy"
)

print("CV Scores:", cv_scores)
print("Mean CV Accuracy:", cv_scores.mean())

#Decision Tree
decision_tree = Pipeline([
    ("preprocessor", preprocessor),
    ("model", DecisionTreeClassifier(
        max_depth=4,
        random_state=42,
        class_weight="balanced"
    ))
])

decision_tree.fit(X_train, y_train)

dt_pred = decision_tree.predict(X_val)

print("Decision Tree Accuracy:", accuracy_score(y_val, dt_pred))
print("F1 Score:", f1_score(y_val, dt_pred, zero_division=0))
print(confusion_matrix(y_val, dt_pred))

#Random Forest
random_forest = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestClassifier(
        n_estimators=200,
        max_depth=6,
        random_state=42,
        class_weight="balanced"
    ))
])

random_forest.fit(X_train, y_train)

rf_pred = random_forest.predict(X_val)

print("Random Forest Accuracy:", accuracy_score(y_val, rf_pred))
print("F1 Score:", f1_score(y_val, rf_pred, zero_division=0))
print(confusion_matrix(y_val, rf_pred))

#Compare Models
models = {
    "Logistic Regression": logistic_model,
    "Decision Tree": decision_tree,
    "Random Forest": random_forest
}

results = []

for name, model in models.items():
    pred = model.predict(X_val)
    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_val, pred),
        "Precision": precision_score(y_val, pred, zero_division=0),
        "Recall": recall_score(y_val, pred, zero_division=0),
        "F1 Score": f1_score(y_val, pred, zero_division=0)
    })

results_df = pd.DataFrame(results)
print(results_df.sort_values("F1 Score", ascending=False))

# Commented out IPython magic to ensure Python compatibility.
#XGBoost
# %pip install xgboost

from xgboost import XGBClassifier

xgb_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", XGBClassifier(
        n_estimators=200,
        max_depth=3,
        learning_rate=0.05,
        eval_metric="logloss",
        random_state=42
    ))
])

xgb_model.fit(X_train, y_train)

xgb_pred = xgb_model.predict(X_val)

print("XGBoost Accuracy:", accuracy_score(y_val, xgb_pred))
print("Precision:", precision_score(y_val, xgb_pred, zero_division=0))
print("Recall:", recall_score(y_val, xgb_pred, zero_division=0))
print("F1 Score:", f1_score(y_val, xgb_pred, zero_division=0))

#Final Prediction on Test Dataset
logistic_model.fit(X, y)

test_predictions = logistic_model.predict(X_test)

submission = pd.DataFrame({
    "Loan_ID": test["Loan_ID"],
    "Loan_Status": np.where(test_predictions == 1, "Y", "N")
})

submission.to_csv("loan_prediction_submission.csv", index=False)

print(submission.head())
print("File saved successfully")

